apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mkcert-issuer
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ca:
    secretName: ca-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-tls-cert
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  privateKey:
    rotationPolicy: Always
  secretName: ca-tls-secret
  dnsNames:
    - localhost
    - example.io
    - k8s.local
    - argocd.local
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: mkcert-issuer
    kind: ClusterIssuer